title: You might not need jQuery plugins
description: When youmightnotneedjquery you also might not need jQuery plugins. 
author: 
baseurl: "/you-might-not-need-jquery-plugins"
markdown: redcarpet
google_analytics:
highlighter: pygments
## Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
